### ISSUE TITLE
Using adapter with multihost

### ISSUE THREAD

**Issue by wolwo3** [iobroker-community-adapters/ioBroker.rpi2#40]
Hello,
I try to switch my GPIO's on a slave of my multihost system.
Currently it is not possible to install multiple instances on IOBroker so I can't switch any GPIO on a multihosts slave.
Also it is not possible to get any other values of the slave. Is there anything I can do about it. Is a multiinstance feature planed?
Main target is to switch the IO's out of Javascript- Blockly.

KR
Wolfgang

**Comment by Apollon77** [comment]
you vcan only have one adapter instance per host, right ... so you can have multiple instances -one per host.

**Comment by ossd** [comment]
At the moment, there is an error, when you try to install the adapter on a slave when you already have one on the master: 
`iobroker host.master-raspi error: this adapter does not allow multiple instances on one host`
Is this error correct? Because I like to have two instances, one per host. When I read your answer, it sounds like it should work. Thanks

**Comment by Apollon77** [comment]
Please make sure to select the correct slave in Admin on top before you install the adapter ... it seems that admin tried to install it on the master or other host where already an instance is installed

**Comment by ossd** [comment]
Oh yes. The "add" adapter button ask for the host, but this is not enough. Selecting the slave in top menu first, solved it. Thanks
