### ISSUE TITLE
GPIO with new installer

### ISSUE THREAD

**Issue by MiJo112** [iobroker-community-adapters/ioBroker.rpi2#6]
The new Installer install iobroker without root.
How can i control the GPIO?

> Error:  GPIO is not initialized!

(RPI 2, iobroker slave, Update:latest)
On console works with the pi user `gpio readall` and `gpio write 3 1`...

**Comment by janfromberlin** [comment]
Just an idea, because I had the same problem: is the user that is running iobroker a member of the group `gpio`?

`top`  should reveal under which account the iobroker processes are running

`groups iobrokerusername` displays the group memberships. It should include all resources it needs to access, like bluetooth, audio, gpio, tty ...

If gpio is missing, then
`sudo groups -a -G gpio iobrokerusername`
